// 전국 인기 캠핑장 데이터
// coords: [위도, 경도] · 날씨 조회용
// booking: 예약/정보 링크 (고캠핑 검색 또는 공식 페이지)
window.CAMPGROUNDS = [
  {
    name: "자라섬 오토캠핑장",
    region: "경기",
    tags: ["강", "가족", "오토캠핑"],
    desc: "북한강이 감싸 안는 섬 캠핑장. 재즈페스티벌로 유명한 자라섬에서 즐기는 사계절 캠핑.",
    coords: [37.8166, 127.5246],
    booking: "https://jarasum.campingin.co.kr/",
    emoji: "🏝️",
  },
  {
    name: "남이섬 캠핑장",
    region: "강원",
    tags: ["강", "숲", "이색"],
    desc: "메타세쿼이아 길과 강변 풍경이 어우러진 낭만 캠핑.",
    coords: [37.7903, 127.5256],
    booking: "https://namisum.com/",
    emoji: "🌲",
  },
  {
    name: "가평 유명산자연휴양림",
    region: "경기",
    tags: ["산", "계곡", "휴양림"],
    desc: "맑은 계곡물과 울창한 숲이 어우러진 국립 휴양림 캠핑장.",
    coords: [37.6406, 127.4561],
    booking: "https://www.foresttrip.go.kr/",
    emoji: "⛰️",
  },
  {
    name: "강릉 경포해변 솔밭",
    region: "강원",
    tags: ["바다", "해변", "백패킹"],
    desc: "동해 일출과 솔숲, 경포호수까지. 강릉 여행 베이스캠프.",
    coords: [37.8052, 128.9006],
    booking: "https://www.gocamping.or.kr/bsd/cmpgnd/search.do?keyword=경포",
    emoji: "🌊",
  },
  {
    name: "속초 설악산 소공원",
    region: "강원",
    tags: ["산", "단풍", "트레킹"],
    desc: "설악산 자락, 단풍 시즌 최고의 인기. 케이블카·울산바위 코앞.",
    coords: [38.1689, 128.4965],
    booking: "https://www.knps.or.kr/",
    emoji: "🍁",
  },
  {
    name: "태안 만리포 오토캠핑",
    region: "충남",
    tags: ["바다", "서해", "낙조"],
    desc: "서해 최고의 낙조와 넓은 백사장. 해수욕과 캠핑을 동시에.",
    coords: [36.7878, 126.1469],
    booking: "https://www.gocamping.or.kr/bsd/cmpgnd/search.do?keyword=만리포",
    emoji: "🌅",
  },
  {
    name: "단양 소선암 오토캠핑장",
    region: "충북",
    tags: ["계곡", "강", "가족"],
    desc: "남한강과 기암절벽이 빚어낸 절경. 물놀이 명소.",
    coords: [36.8898, 128.3403],
    booking: "https://www.gocamping.or.kr/bsd/cmpgnd/search.do?keyword=소선암",
    emoji: "🏞️",
  },
  {
    name: "포항 영일대 해상누각",
    region: "경북",
    tags: ["바다", "동해", "야경"],
    desc: "동해 일출과 해상누각 야경이 어우러진 도심 속 바다 캠핑.",
    coords: [36.0594, 129.3781],
    booking: "https://www.gocamping.or.kr/bsd/cmpgnd/search.do?keyword=영일대",
    emoji: "🌃",
  },
  {
    name: "거제 학동흑진주몽돌해변",
    region: "경남",
    tags: ["바다", "남해", "몽돌"],
    desc: "파도에 구르는 몽돌 소리가 자장가가 되는 남해 캠핑.",
    coords: [34.7686, 128.6453],
    booking: "https://www.gocamping.or.kr/bsd/cmpgnd/search.do?keyword=학동",
    emoji: "🪨",
  },
  {
    name: "남해 두모마을 오토캠핑장",
    region: "경남",
    tags: ["바다", "남해", "유채"],
    desc: "다랭이 풍경과 봄철 유채꽃, 카약 체험까지 즐기는 힐링 캠핑.",
    coords: [34.7136, 127.9181],
    booking: "https://www.gocamping.or.kr/bsd/cmpgnd/search.do?keyword=두모",
    emoji: "🌼",
  },
  {
    name: "지리산 백무동 야영장",
    region: "경남",
    tags: ["산", "계곡", "트레킹"],
    desc: "지리산 천왕봉 등산 들머리. 시원한 계곡과 깊은 숲.",
    coords: [35.3267, 127.7392],
    booking: "https://www.knps.or.kr/",
    emoji: "🥾",
  },
  {
    name: "변산반도 고사포 야영장",
    region: "전북",
    tags: ["바다", "서해", "솔숲"],
    desc: "해송 숲과 넓은 갯벌, 채석강이 가까운 변산반도 명소.",
    coords: [35.6669, 126.4750],
    booking: "https://www.knps.or.kr/",
    emoji: "🌲",
  },
  {
    name: "순천만 갈대밭 오토캠핑",
    region: "전남",
    tags: ["습지", "노을", "생태"],
    desc: "세계적인 갈대 습지와 황금빛 노을. 생태 여행 베이스캠프.",
    coords: [34.8853, 127.5097],
    booking: "https://www.gocamping.or.kr/bsd/cmpgnd/search.do?keyword=순천만",
    emoji: "🌾",
  },
  {
    name: "보성 율포해수욕장 캠핑",
    region: "전남",
    tags: ["바다", "남해", "녹차"],
    desc: "보성 녹차밭과 해수녹차탕, 잔잔한 율포 바다가 함께.",
    coords: [34.6597, 127.1183],
    booking: "https://www.gocamping.or.kr/bsd/cmpgnd/search.do?keyword=율포",
    emoji: "🍵",
  },
  {
    name: "제주 함덕 오토캠핑장",
    region: "제주",
    tags: ["바다", "에메랄드", "가족"],
    desc: "에메랄드빛 함덕 해변과 서우봉. 제주 동부 여행의 중심.",
    coords: [33.5435, 126.6694],
    booking: "https://www.gocamping.or.kr/bsd/cmpgnd/search.do?keyword=함덕",
    emoji: "🏖️",
  },
  {
    name: "제주 김녕 해수욕장 야영장",
    region: "제주",
    tags: ["바다", "별빛", "풍력"],
    desc: "맑은 바다와 풍력발전기, 밤이면 쏟아지는 별. 제주 감성 캠핑.",
    coords: [33.5577, 126.7560],
    booking: "https://www.gocamping.or.kr/bsd/cmpgnd/search.do?keyword=김녕",
    emoji: "✨",
  },
  {
    name: "춘천 강촌 오토캠핑장",
    region: "강원",
    tags: ["강", "레저", "가족"],
    desc: "북한강 수상레저와 자전거길. 서울 근교 인기 캠핑지.",
    coords: [37.8147, 127.6261],
    booking: "https://www.gocamping.or.kr/bsd/cmpgnd/search.do?keyword=강촌",
    emoji: "🚣",
  },
  {
    name: "인제 자작나무숲 캠핑",
    region: "강원",
    tags: ["숲", "산", "설경"],
    desc: "하얀 자작나무가 빚어내는 이국적 풍경. 겨울 설경 명소.",
    coords: [38.0660, 128.2030],
    booking: "https://www.gocamping.or.kr/bsd/cmpgnd/search.do?keyword=자작나무",
    emoji: "🌳",
  },
];
