// 전국 인기 캠핑장 데이터 (17개 시·도, 55곳)
// coords: [위도, 경도] · 날씨 조회용
// booking: 예약/정보 링크 (공식 페이지 또는 고캠핑 검색)
// 출처: 한국관광공사 고캠핑(gocamping.or.kr) 및 공식 캠핑장 페이지 기반 조사
window.CAMPGROUNDS = [
  {
    name: "자라섬 오토캠핑장",
    region: "경기",
    address: "경기 가평군 가평읍 자라섬로 60",
    coords: [37.8157, 127.5232],
    tags: ["강", "섬", "가족", "오토캠핑"],
    desc: "북한강이 감싸 안는 섬에서 즐기는 낭만 캠핑.",
    booking: "https://www.gocamping.or.kr/bsd/cmpgnd/search.do?keyword=%EC%9E%90%EB%9D%BC%EC%84%AC",
    emoji: "🏝️",
  },
  {
    name: "가평 다온캠핑장",
    region: "경기",
    address: "경기 가평군 북면 백둔로 199",
    coords: [37.9215, 127.4731],
    tags: ["계곡", "숲", "가족", "물놀이"],
    desc: "맑은 계곡물과 온수 수영장을 갖춘 숲속 캠핑장.",
    booking: "https://daoncamp.com/",
    emoji: "🌲",
  },
  {
    name: "산정호수 자연농원 캠핑장",
    region: "경기",
    address: "경기 포천시 영북면 산정호수로 411",
    coords: [38.0610, 127.3245],
    tags: ["호수", "산", "가족", "단풍"],
    desc: "산정호수 둘레의 가을 단풍이 아름다운 캠핑장.",
    booking: "https://www.gocamping.or.kr/bsd/cmpgnd/search.do?keyword=%EC%82%B0%EC%A0%95%ED%98%B8%EC%88%98",
    emoji: "🍁",
  },
  {
    name: "양평 중미산자연휴양림 야영장",
    region: "경기",
    address: "경기 양평군 옥천면 중미산로 152",
    coords: [37.5783, 127.4470],
    tags: ["산", "숲", "휴양림", "가족"],
    desc: "별 보기 좋은 청정 숲속 휴양림 야영장.",
    booking: "https://www.foresttrip.go.kr/",
    emoji: "🌳",
  },
  {
    name: "난지 캠핑장",
    region: "서울",
    address: "서울 마포구 한강난지로 162 난지한강공원",
    coords: [37.5667, 126.8770],
    tags: ["강", "가족", "글램핑", "오토캠핑"],
    desc: "한강 도심에서 즐기는 도시형 캠핑의 정석.",
    booking: "https://www.gocamping.or.kr/bsd/cmpgnd/search.do?keyword=%EB%82%9C%EC%A7%80",
    emoji: "🌃",
  },
  {
    name: "노을 캠핑장",
    region: "서울",
    address: "서울 마포구 하늘공원로 108-1 노을공원",
    coords: [37.5688, 126.8836],
    tags: ["노을", "가족", "숲"],
    desc: "월드컵공원 언덕에서 서울 노을을 품는 캠핑장.",
    booking: "https://www.gocamping.or.kr/bsd/cmpgnd/search.do?keyword=%EB%85%B8%EC%9D%84%EC%BA%A0%ED%95%91%EC%9E%A5",
    emoji: "🌅",
  },
  {
    name: "왕산 가족 오토캠핑장",
    region: "인천",
    address: "인천 중구 을왕동 678-179",
    coords: [37.4490, 126.3690],
    tags: ["바다", "해변", "숲", "오토캠핑"],
    desc: "왕산해변 솔숲에서 즐기는 서해 바다 캠핑.",
    booking: "https://www.gocamping.or.kr/bsd/cmpgnd/search.do?keyword=%EC%99%95%EC%82%B0",
    emoji: "🏖️",
  },
  {
    name: "을왕리 솔트 캠핑장",
    region: "인천",
    address: "인천 중구 용유서로302번길 50-21",
    coords: [37.4470, 126.3730],
    tags: ["바다", "노을", "글램핑", "가족"],
    desc: "을왕리 서해 낙조를 코앞에서 감상하는 캠핑장.",
    booking: "https://www.gocamping.or.kr/bsd/cmpgnd/search.do?keyword=%EC%9D%84%EC%99%95%EB%A6%AC%20%EC%86%94%ED%8A%B8",
    emoji: "🌅",
  },
  {
    name: "강화 동막해변 캠핑장",
    region: "인천",
    address: "인천 강화군 화도면 해안남로1481번길 12",
    coords: [37.5946, 126.4170],
    tags: ["바다", "갯벌", "노을", "가족"],
    desc: "강화 갯벌과 일몰이 어우러진 서해 캠핑장.",
    booking: "https://www.gocamping.or.kr/bsd/cmpgnd/search.do?keyword=%EB%8F%99%EB%A7%89",
    emoji: "🌅",
  },
  {
    name: "장호비치 캠핑장",
    region: "강원",
    address: "강원 삼척시 근덕면 삼척로 2116",
    coords: [37.3127, 129.3270],
    tags: ["바다", "해변", "물놀이", "오토캠핑"],
    desc: "한국의 나폴리, 에메랄드빛 장호항 바다 캠핑.",
    booking: "http://www.janghocamping.kr/",
    emoji: "🌊",
  },
  {
    name: "추암 오토캠핑장",
    region: "강원",
    address: "강원 동해시 촛대바위길 28",
    coords: [37.4793, 129.1450],
    tags: ["바다", "일출", "오토캠핑"],
    desc: "촛대바위 일출 명소 바로 옆 동해 캠핑장.",
    booking: "https://www.gocamping.or.kr/bsd/cmpgnd/search.do?keyword=%EC%B6%94%EC%95%94",
    emoji: "🌅",
  },
  {
    name: "양양 죽도 오토캠핑장",
    region: "강원",
    address: "강원 양양군 현남면 인구중앙길 88",
    coords: [37.9710, 128.7720],
    tags: ["바다", "해변", "물놀이", "오토캠핑"],
    desc: "서핑 성지 죽도해변 앞바다를 누리는 캠핑장.",
    booking: "https://www.gocamping.or.kr/bsd/cmpgnd/search.do?keyword=%EC%A3%BD%EB%8F%84",
    emoji: "🏄",
  },
  {
    name: "고성 자작도 캠핑장",
    region: "강원",
    address: "강원 고성군 죽왕면 삼포해변길 21",
    coords: [38.2620, 128.5570],
    tags: ["바다", "해변", "물놀이", "가족"],
    desc: "깨끗한 백사장 삼포해변을 품은 동해 캠핑장.",
    booking: "https://www.gocamping.or.kr/bsd/cmpgnd/search.do?keyword=%EC%9E%90%EC%9E%91%EB%8F%84",
    emoji: "🏖️",
  },
  {
    name: "설악동 야영장",
    region: "강원",
    address: "강원 속초시 설악산로 1055",
    coords: [38.1690, 128.5170],
    tags: ["산", "숲", "단풍", "백패킹"],
    desc: "설악산 단풍을 코앞에서 즐기는 국립공원 야영장.",
    booking: "https://www.knps.or.kr/",
    emoji: "🍁",
  },
  {
    name: "홍천강 오토캠핑장",
    region: "강원",
    address: "강원 홍천군 서면 한치골길 184",
    coords: [37.7140, 127.6360],
    tags: ["강", "물놀이", "가족", "오토캠핑"],
    desc: "맑은 홍천강에서 물놀이를 즐기는 강변 캠핑장.",
    booking: "https://www.gocamping.or.kr/bsd/cmpgnd/search.do?keyword=%ED%99%8D%EC%B2%9C%EA%B0%95",
    emoji: "🚣",
  },
  {
    name: "천동 오토캠핑장",
    region: "충북",
    address: "충북 단양군 단양읍 다리안로 534",
    coords: [36.9320, 128.3820],
    tags: ["계곡", "산", "물놀이", "오토캠핑"],
    desc: "소백산 다리안계곡 맑은 물가의 시원한 캠핑장.",
    booking: "https://www.dytc.or.kr/main/41",
    emoji: "🏞️",
  },
  {
    name: "대강 오토캠핑장",
    region: "충북",
    address: "충북 단양군 대강면 사인암로 683-77",
    coords: [36.9210, 128.2870],
    tags: ["계곡", "산", "단풍", "오토캠핑"],
    desc: "명승 사인암 인근 단양 산자락의 한적한 캠핑장.",
    booking: "https://www.dytc.or.kr/main/41",
    emoji: "🪨",
  },
  {
    name: "충주호 캠핑월드",
    region: "충북",
    address: "충북 충주시 종민동 산 1-1",
    coords: [37.0070, 127.9430],
    tags: ["호수", "산", "가족", "단풍"],
    desc: "충주호 호반의 탁 트인 전망을 즐기는 캠핑장.",
    booking: "https://www.gocamping.or.kr/bsd/cmpgnd/search.do?keyword=%EC%B6%A9%EC%A3%BC%ED%98%B8",
    emoji: "🏞️",
  },
  {
    name: "안면도 송도 오토캠핑장",
    region: "충남",
    address: "충남 태안군 안면읍 안면대로 3",
    coords: [36.5130, 126.3320],
    tags: ["바다", "숲", "노을", "오토캠핑"],
    desc: "안면도 소나무숲과 서해 낙조를 누리는 캠핑장.",
    booking: "http://songdocamping.anmyondo.co.kr/",
    emoji: "🌅",
  },
  {
    name: "보령 무창포 오토캠핑장",
    region: "충남",
    address: "충남 보령시 웅천읍 열린바다1길 26",
    coords: [36.2480, 126.5260],
    tags: ["바다", "해변", "물놀이", "오토캠핑"],
    desc: "신비의 바닷길로 유명한 무창포해변 캠핑장.",
    booking: "https://www.gocamping.or.kr/bsd/cmpgnd/search.do?keyword=%EB%AC%B4%EC%B0%BD%ED%8F%AC",
    emoji: "🌊",
  },
  {
    name: "오서산 자연휴양림 야영장",
    region: "충남",
    address: "충남 보령시 청라면 오서산길 580",
    coords: [36.3850, 126.6480],
    tags: ["산", "숲", "휴양림", "단풍"],
    desc: "은빛 억새로 물드는 오서산 숲속 야영장.",
    booking: "https://www.foresttrip.go.kr/",
    emoji: "🌾",
  },
  {
    name: "대전 만인산 오토캠핑장",
    region: "대전",
    address: "대전 동구 산내로 1450",
    coords: [36.2440, 127.4690],
    tags: ["산", "숲", "가족", "오토캠핑"],
    desc: "만인산 푸른 숲에 안긴 대전 도심 근교 캠핑장.",
    booking: "https://www.gocamping.or.kr/bsd/cmpgnd/search.do?keyword=%EB%A7%8C%EC%9D%B8%EC%82%B0",
    emoji: "🌲",
  },
  {
    name: "장태산 자연휴양림 야영장",
    region: "대전",
    address: "대전 서구 장안로 461",
    coords: [36.2270, 127.3070],
    tags: ["숲", "휴양림", "산책", "가족"],
    desc: "메타세쿼이아 숲길이 일품인 휴양림 야영장.",
    booking: "https://www.foresttrip.go.kr/",
    emoji: "🌳",
  },
  {
    name: "세종 합강캠핑장",
    region: "세종",
    address: "세종 연기면 태산로 329",
    coords: [36.5230, 127.3110],
    tags: ["강", "가족", "오토캠핑", "물놀이"],
    desc: "금강 합류점 너른 강변에 자리한 가족 캠핑장.",
    booking: "https://www.sjfmc.or.kr/camping/sub01_01.do",
    emoji: "🏞️",
  },
  {
    name: "세종 영평사 캠핑장",
    region: "세종",
    address: "세종 장군면 영평사길 124",
    coords: [36.4870, 127.2230],
    tags: ["숲", "산", "가족", "단풍"],
    desc: "구절초 향 가득한 세종 산자락의 조용한 캠핑장.",
    booking: "https://www.gocamping.or.kr/bsd/cmpgnd/search.do?keyword=%EC%84%B8%EC%A2%85%20%EC%BA%A0%ED%95%91%EC%9E%A5",
    emoji: "🌼",
  },
  {
    name: "경주 초우 오토캠핑장",
    region: "경북",
    address: "경북 경주시 보불로 391",
    coords: [35.8230, 129.2900],
    tags: ["숲", "가족", "오토캠핑"],
    desc: "보문관광단지 인근, 경주 여행 거점 캠핑장.",
    booking: "https://www.gocamping.or.kr/bsd/cmpgnd/search.do?keyword=%EC%B4%88%EC%9A%B0",
    emoji: "🌲",
  },
  {
    name: "포항 산누리 오토캠핑장",
    region: "경북",
    address: "경북 포항시 북구 죽장면 하옥로 1736",
    coords: [36.2050, 129.1230],
    tags: ["계곡", "산", "물놀이", "오토캠핑"],
    desc: "청정 하옥계곡 물놀이를 즐기는 산속 캠핑장.",
    booking: "https://www.gocamping.or.kr/bsd/cmpgnd/search.do?keyword=%EC%82%B0%EB%88%84%EB%A6%AC",
    emoji: "🏞️",
  },
  {
    name: "울진 백암온천 오토캠핑장",
    region: "경북",
    address: "경북 울진군 온정면 온천로 144",
    coords: [36.6760, 129.3550],
    tags: ["산", "숲", "휴양림", "가족"],
    desc: "백암온천을 곁들이는 울진 산자락 캠핑장.",
    booking: "https://www.gocamping.or.kr/bsd/cmpgnd/search.do?keyword=%EB%B0%B1%EC%95%94",
    emoji: "🍵",
  },
  {
    name: "안동 호반 자연휴양림 야영장",
    region: "경북",
    address: "경북 안동시 도산면 퇴계로 1714-12",
    coords: [36.7460, 128.8470],
    tags: ["호수", "숲", "휴양림", "단풍"],
    desc: "안동호 물빛을 품은 고즈넉한 휴양림 야영장.",
    booking: "https://www.foresttrip.go.kr/",
    emoji: "🏞️",
  },
  {
    name: "팔공산 야영장",
    region: "대구",
    address: "대구 동구 팔공산로 1390",
    coords: [35.9970, 128.6960],
    tags: ["산", "숲", "단풍", "가족"],
    desc: "팔공산 단풍 명소를 끼고 즐기는 도심 근교 캠핑.",
    booking: "https://www.gocamping.or.kr/bsd/cmpgnd/search.do?keyword=%ED%8C%94%EA%B3%B5%EC%82%B0",
    emoji: "🍁",
  },
  {
    name: "대구 사문진 캠핑장",
    region: "대구",
    address: "대구 달성군 화원읍 사문진로 232",
    coords: [35.7910, 128.4630],
    tags: ["강", "노을", "가족", "오토캠핑"],
    desc: "낙동강 사문진나루 노을이 흐르는 강변 캠핑장.",
    booking: "https://www.gocamping.or.kr/bsd/cmpgnd/search.do?keyword=%EC%82%AC%EB%AC%B8%EC%A7%84",
    emoji: "🌅",
  },
  {
    name: "강동 오토캠핑장",
    region: "울산",
    address: "울산 북구 산하동 산 156",
    coords: [35.6390, 129.4540],
    tags: ["바다", "일출", "오토캠핑", "낚시"],
    desc: "몽돌 해변과 동해 일출이 펼쳐지는 캠핑장.",
    booking: "https://www.gocamping.or.kr/bsd/cmpgnd/search.do?keyword=%EA%B0%95%EB%8F%99",
    emoji: "🌅",
  },
  {
    name: "진하 오토캠핑장",
    region: "울산",
    address: "울산 울주군 서생면 진하해변길 137-1",
    coords: [35.3700, 129.3380],
    tags: ["바다", "해변", "물놀이", "오토캠핑"],
    desc: "명선도가 보이는 진하해변 앞 가족 캠핑장.",
    booking: "https://www.gocamping.or.kr/bsd/cmpgnd/search.do?keyword=%EC%A7%84%ED%95%98",
    emoji: "🏖️",
  },
  {
    name: "송정 오토캠핑장",
    region: "부산",
    address: "부산 해운대구 송정해변로 62",
    coords: [35.1790, 129.1990],
    tags: ["바다", "해변", "물놀이", "오토캠핑"],
    desc: "서핑으로 유명한 송정해변 바로 앞 도심 캠핑장.",
    booking: "https://www.gocamping.or.kr/bsd/cmpgnd/search.do?keyword=%EC%86%A1%EC%A0%95%20%EC%BA%A0%ED%95%91",
    emoji: "🌊",
  },
  {
    name: "대저생태공원 캠핑장",
    region: "부산",
    address: "부산 강서구 대저1동 1180",
    coords: [35.1990, 128.9670],
    tags: ["강", "가족", "오토캠핑", "물놀이"],
    desc: "낙동강 생태공원 너른 잔디밭의 가족 캠핑장.",
    booking: "https://www.daejeocamping.com/",
    emoji: "🌾",
  },
  {
    name: "임랑해수욕장 캠핑장",
    region: "부산",
    address: "부산 기장군 장안읍 임랑리",
    coords: [35.3210, 129.2660],
    tags: ["바다", "해변", "노을", "차박"],
    desc: "백사장 차박이 가능한 부산 임랑 바다 캠핑.",
    booking: "https://www.gocamping.or.kr/bsd/cmpgnd/search.do?keyword=%EC%9E%84%EB%9E%91",
    emoji: "🏖️",
  },
  {
    name: "변산 오토캠핑장",
    region: "전북",
    address: "전북 부안군 변산면 변산해변로 51",
    coords: [35.6650, 126.5170],
    tags: ["바다", "해변", "노을", "오토캠핑"],
    desc: "변산해변 붉은 석양이 물드는 서해 캠핑장.",
    booking: "https://www.bscamping.co.kr/",
    emoji: "🌅",
  },
  {
    name: "지리산 국립공원 덕동 야영장",
    region: "전북",
    address: "전북 남원시 산내면 천왕봉로 626",
    coords: [35.3360, 127.6280],
    tags: ["산", "계곡", "숲", "백패킹"],
    desc: "지리산 뱀사골 자락의 시원한 계곡 야영장.",
    booking: "https://www.knps.or.kr/",
    emoji: "⛰️",
  },
  {
    name: "덕유산 덕유대 야영장",
    region: "전북",
    address: "전북 무주군 설천면 구천동1로 159",
    coords: [35.8870, 127.7430],
    tags: ["산", "계곡", "단풍", "설경"],
    desc: "구천동 계곡 곁, 사계절 빛나는 국립공원 야영장.",
    booking: "https://www.knps.or.kr/",
    emoji: "❄️",
  },
  {
    name: "담양 금성산성 오토캠핑장",
    region: "전남",
    address: "전남 담양군 금성면 새덕굴길 135-88",
    coords: [35.3320, 127.0090],
    tags: ["산", "숲", "단풍", "오토캠핑"],
    desc: "대숲 산책로를 품은 금성산성 아래 캠핑장.",
    booking: "http://www.gscamp.co.kr/",
    emoji: "🌲",
  },
  {
    name: "여수 사도 오토캠핑장",
    region: "전남",
    address: "전남 여수시 화정면 낭도리",
    coords: [34.6020, 127.5320],
    tags: ["바다", "섬", "노을", "오토캠핑"],
    desc: "다도해 노을이 아름다운 여수 섬마을 캠핑장.",
    booking: "https://www.gocamping.or.kr/bsd/cmpgnd/search.do?keyword=%EC%97%AC%EC%88%98%20%EC%BA%A0%ED%95%91",
    emoji: "🌅",
  },
  {
    name: "고흥 나로도 우주발사전망대 캠핑장",
    region: "전남",
    address: "전남 고흥군 봉래면 외나로도해안길 626",
    coords: [34.4570, 127.4530],
    tags: ["바다", "일출", "오토캠핑", "낚시"],
    desc: "남해 수평선 일출을 마주하는 나로도 캠핑장.",
    booking: "https://www.gocamping.or.kr/bsd/cmpgnd/search.do?keyword=%EB%82%98%EB%A1%9C%EB%8F%84",
    emoji: "🌅",
  },
  {
    name: "무등산 도원 야영장",
    region: "광주",
    address: "광주 북구 무등로 1550",
    coords: [35.1340, 126.9970],
    tags: ["산", "계곡", "숲", "단풍"],
    desc: "무등산 도원계곡 자락의 자연친화 야영장.",
    booking: "https://www.knps.or.kr/",
    emoji: "⛰️",
  },
  {
    name: "광주 시민의 숲 야영장",
    region: "광주",
    address: "광주 광산구 첨단연신로 510",
    coords: [35.2230, 126.8470],
    tags: ["숲", "가족", "오토캠핑"],
    desc: "도심 속 푸른 숲에서 즐기는 접근성 좋은 캠핑장.",
    booking: "https://www.gocamping.or.kr/bsd/cmpgnd/search.do?keyword=%EC%8B%9C%EB%AF%BC%EC%9D%98%20%EC%88%B2",
    emoji: "🌳",
  },
  {
    name: "고성 남산공원 오토캠핑장",
    region: "경남",
    address: "경남 고성군 고성읍 공룡로 3165",
    coords: [34.9650, 128.3290],
    tags: ["바다", "노을", "오토캠핑", "가족"],
    desc: "해지개 해안둘레길과 바다 야경을 품은 캠핑장.",
    booking: "https://www.gocamping.or.kr/bsd/cmpgnd/search.do?keyword=%EB%82%A8%EC%82%B0%EA%B3%B5%EC%9B%90",
    emoji: "🌅",
  },
  {
    name: "거제 학동 자동차 야영장",
    region: "경남",
    address: "경남 거제시 동부면 거제대로 1232",
    coords: [34.7720, 128.6720],
    tags: ["바다", "해변", "물놀이", "오토캠핑"],
    desc: "몽돌해변 파도소리가 들리는 거제 바다 캠핑장.",
    booking: "https://www.gocamping.or.kr/bsd/cmpgnd/search.do?keyword=%ED%95%99%EB%8F%99",
    emoji: "🌊",
  },
  {
    name: "남해 상주은모래비치 오토캠핑장",
    region: "경남",
    address: "경남 남해군 상주면 상주로 17-4",
    coords: [34.7080, 127.9970],
    tags: ["바다", "해변", "물놀이", "가족"],
    desc: "은빛 모래 상주해변을 품은 남해 가족 캠핑장.",
    booking: "https://www.gocamping.or.kr/bsd/cmpgnd/search.do?keyword=%EC%83%81%EC%A3%BC%EC%9D%80%EB%AA%A8%EB%9E%98",
    emoji: "🏖️",
  },
  {
    name: "통제영 오토캠핑장",
    region: "경남",
    address: "경남 통영시 한산면 한산일주로 171",
    coords: [34.7790, 128.4870],
    tags: ["바다", "섬", "오토캠핑", "가족"],
    desc: "한산도 역사와 다도해 풍광을 누리는 섬 캠핑장.",
    booking: "https://www.gocamping.or.kr/bsd/cmpgnd/search.do?keyword=%ED%86%B5%EC%A0%9C%EC%98%81",
    emoji: "🏝️",
  },
  {
    name: "국립지리산 자연휴양림 야영장",
    region: "경남",
    address: "경남 함양군 마천면 음정길 152",
    coords: [35.3680, 127.6240],
    tags: ["산", "계곡", "숲", "휴양림"],
    desc: "지리산 깊은 골 맑은 계곡의 휴양림 야영장.",
    booking: "https://www.foresttrip.go.kr/",
    emoji: "🌲",
  },
  {
    name: "거제 옥계 오토캠핑장",
    region: "경남",
    address: "경남 거제시 하청면 칠천로 265-17",
    coords: [34.9460, 128.6390],
    tags: ["바다", "낚시", "노을", "오토캠핑"],
    desc: "칠천도 잔잔한 바다와 낚시를 즐기는 캠핑장.",
    booking: "https://www.gocamping.or.kr/bsd/cmpgnd/search.do?keyword=%EC%98%A5%EA%B3%84",
    emoji: "🐟",
  },
  {
    name: "곽지해수욕장 오토캠핑장",
    region: "제주",
    address: "제주 제주시 애월읍 곽지리 1565",
    coords: [33.4510, 126.3050],
    tags: ["바다", "해변", "노을", "물놀이"],
    desc: "에메랄드빛 곽지해변에서 즐기는 제주 바다 캠핑.",
    booking: "https://www.gocamping.or.kr/bsd/cmpgnd/search.do?keyword=%EA%B3%BD%EC%A7%80",
    emoji: "🌊",
  },
  {
    name: "함덕 서우봉해변 캠핑장",
    region: "제주",
    address: "제주 제주시 조천읍 조함해안로 525",
    coords: [33.5430, 126.6690],
    tags: ["바다", "해변", "노을", "가족"],
    desc: "서우봉과 옥빛 바다가 어우러진 함덕 캠핑장.",
    booking: "https://www.gocamping.or.kr/bsd/cmpgnd/search.do?keyword=%ED%95%A8%EB%8D%95",
    emoji: "🏝️",
  },
  {
    name: "모구리 야영장",
    region: "제주",
    address: "제주 서귀포시 성산읍 난산리 2207",
    coords: [33.3760, 126.8720],
    tags: ["숲", "산", "가족", "오토캠핑"],
    desc: "오름과 들판에 둘러싸인 제주 동부 숲속 야영장.",
    booking: "https://www.gocamping.or.kr/bsd/cmpgnd/search.do?keyword=%EB%AA%A8%EA%B5%AC%EB%A6%AC",
    emoji: "🌳",
  },
  {
    name: "돈내코 야영장",
    region: "제주",
    address: "제주 서귀포시 상효동 1459",
    coords: [33.2980, 126.5870],
    tags: ["계곡", "숲", "산", "물놀이"],
    desc: "한라산 자락 돈내코계곡 청정 숲속 야영장.",
    booking: "https://www.gocamping.or.kr/bsd/cmpgnd/search.do?keyword=%EB%8F%88%EB%82%B4%EC%BD%94",
    emoji: "🏞️",
  },
  {
    name: "김녕해수욕장 야영장",
    region: "제주",
    address: "제주 제주시 구좌읍 김녕로21길 8",
    coords: [33.5580, 126.7560],
    tags: ["바다", "해변", "물놀이", "오토캠핑"],
    desc: "투명한 김녕 바다와 풍력발전기 풍경의 캠핑장.",
    booking: "https://www.gocamping.or.kr/bsd/cmpgnd/search.do?keyword=%EA%B9%80%EB%85%95",
    emoji: "🌊",
  },
];
